### PR TITLE
[SDK-3090] Remote screenshotter service support

### PR DESCRIPTION
**Pull request by froodian**
This is an implementation of a command similar to the `matchRemoteImageSnapshot` command from IAM-76 / https://github.com/Appboy/platform/pull/46841 - rewritten on a fork of a more actively maintained, ts-based, image comparison cypress plugin (with a comparison/baseline-updating UI!).  It's working for me locally integrated into platform.  I'm not able to commit my platform side yet due to some tsconfig issues that I hope running the CI workflow (which is in github) on this repo will allow me to repair.

### CODE REVIEW

**Review by cellog — APPROVED** [review]
nice!

**Comment by froodian** [comment]
~look at this, it's even mad at me for hurting the test coverage! I love this repo!~

oh, no, it just can't run coverage because it doesn't have the secrets the base repo had

**Comment by Zaxcoding** [comment]
Looks like it got ported over cleanly to me

**Review by Zaxcoding — APPROVED** [review]

**Comment by froodian** [comment]
i think i have to merge it for github to pick up the workflow revision, all but the step that requires codeclimate are green

**Pull request merged**
